# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a48766c37e9da60a62cd62161252afed2b8e3abfe0928c1ea527e3360a8d9c9ca440ca4957bcd7d77be4e73bf1290cf1f5fb3f01aa5e473f3a5a45dbc4d1cf8

test:
  secret_key_base: 0613a1b15370dc98cffa24d5b466248200b6687595ce4ce3c4465bec918044c47b72287bb87f19be0b5ca0372a139b99bb0b0e41db838f56270acbe51df35605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
